language: node_js
node_js:
  - "6"

install:
  - npm install -g typescript typings
  - typings install dt~node dt~mocha --global
  - npm install

before_script:
  - npm run build

after_success:
  - npm run process
  - cd build
  - git init
  - git remote add origin git@github.com:vinyguedess/vinyguedess.github.io.git
  - git commit -am "${TRAVIS_COMMIT_MESSAGE}"
  - git push origin ${TRAVIS_BRANCH}