language: node_js
node_js:
  - "6"

install:
  - npm install -g typescript typings
  - typings install dt~node dt~mocha --global
  - npm install

before_script:
  - npm run build

after_success:
  - node process.js
  - echo $GITHUB_TOKEN