language: node_js
node_js:
  - "6"

install:
  - npm install -g typescript typings
  - typings install dt~node dt~mocha --global
  - npm install

before_script:
  - npm run build

after_success:
  - node process.js
  - cd out/
  - git init
  - git commit -am "TESTING"
  - git remote add origin https://github.com/vinyguedess/vinyguedess.github.io.git
  - git push -u origin master