language: node_js
node_js:
  - "6"

install:
  - npm install -g typescript typings
  - typings install dt~node dt~mocha --global
  - npm install

before_script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out/
  email: viniciusgued@gmail.com
  name: "Vinicius Guedes"
  target_branch: master
  on:
    branch: master