language: node_js
node_js:
  - "6"

env:
  global:
  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
  - COMMIT_AUTHOR_EMAIL: "viniciusgued@gmail.com"

install:
  - npm install -g typescript typings
  - typings install dt~node dt~mocha --global
  - npm install

before_script:
  - npm run build

after_success:
  - npm run process
  - cd build
  - bash ./../deploy.sh